name: flutter_quiver
description: Keep all your arrows in one place

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0
  contextmenu: ^3.0.0
  dama:
    git: https://github.com/thumbert/dama.git
  date:
    git: https://github.com/thumbert/date.git
  elec:
    git: https://github.com/thumbert/elec.git
  elec_server:
    git: https://github.com/thumbert/elec-server.git
  file_picker: ^5.5.0
  flutter_dotenv: ^5.0.0
  flutter_highlight: ^0.7.0
  flutter_riverpod: ^2.0.0-dev.9
  flutter_svg: ^1.1.5
  flutter_web_plotly:
    git: https://github.com/thumbert/flutter_web_plotly.git
  google_fonts: ^4.0.0
  go_router: ^10.0.0
  http: '>=0.12.0 <1.0.0'
  intl: ^0.18.1
  more: ^4.0.1
  petitparser: ^6.0.0
  pointer_interceptor: '>=0.9.3+4 <1.0.0'
  provider: ^6.0.1
  signals: ^4.0.0
  signals_flutter: ^4.0.0
  table:
    git: https://github.com/thumbert/table.git
  timeseries:
    git: https://github.com/thumbert/timeseries.git
  timezone: '>=0.5.5 <1.0.0'
  tuple: ^2.0.0
  url_launcher: ^6.1.14
  yaru_widgets: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.2.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/quiver.svg

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
    - family: Tangerine
      fonts:
        - asset: assets/fonts/Tangerine-Regular.ttf
          weight: 300
        - asset: assets/fonts/Tangerine-Bold.ttf
          weight: 600
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/UbuntuMono-Bold.ttf
          weight: 700



flutter_native_splash:
  color: "#ffffff"
  image: assets/images/loading.png
  android: false
  ios: false
  web: true
